env:
  browser: true
  es6: true
extends:
  - eslint:recommended
  - plugin:prettier/recommended
  - plugin:@typescript-eslint/eslint-recommended
  - plugin:@typescript-eslint/recommended
  - plugin:@typescript-eslint/recommended-requiring-type-checking
globals:
  Atomics: readonly
  SharedArrayBuffer: readonly
parser: '@typescript-eslint/parser'
parserOptions:
  ecmaVersion: 2018
  sourceType: module
  project: './tsconfig.json'
  impliedStrict: true
plugins:
  - '@typescript-eslint'
rules: {
  "@typescript-eslint/explicit-function-return-type": "off"
}
